#!/usr/bin/env bash

DEVICES=$(mpremote connect list | grep MicroPython | cut -d " " -f 1)

if [ -z $DEVICES ] ; then
  echo "No MicroPython devices found in FS mode"
  exit 1
fi

DEVICE=${DEVICES[0]}

echo "Copying Enviro firmware files to ${DEVICE}"

function create_directory {
  echo -n "> creating directory $1"
  mpremote connect ${DEVICE} mkdir $1 > /dev/null
  if [ $? -eq 0 ] ; then
    echo " .. done!"
  else
    echo " .. already exists, skipping."
  fi
}

function copy {
  for file in $1
  do
    echo -n "> copying file $file"
    mpremote connect ${DEVICE} cp $file $2 > /dev/null
    echo " .. done!"
  done
}


create_directory enviro
create_directory enviro/boards
create_directory enviro/destinations
create_directory enviro/html
create_directory enviro/html/images
create_directory phew
create_directory phew/phew

copy "main.py" :

copy "enviro/*.py" :enviro/

copy "enviro/boards/*.py" :enviro/boards/
copy "enviro/destinations/*.py" :enviro/destinations/

copy "enviro/html/*.html" :enviro/html/
copy "enviro/html/*.js" :enviro/html/
copy "enviro/html/*.css" :enviro/html/

copy "enviro/html/images/*" :enviro/html/images/

copy "phew/__init__.py" :phew/
copy "phew/phew/*.py" :phew/phew/
